### ISSUE TITLE
"There were issues initializing IotaMultiplayer"

### ISSUE THREAD

**Issue by RatherTwinky** [XM666-Dev/IotaMultiplayer#1]
This error message pops up every time I try and load a new game. No mod options are added to the options menu, I've got NMEE installed.

**Comment by XM666-Dev** [comment]
Oh, check whether you are using Noita beta branch? This mod is made on beta branch
Pls take screenshot with this mod enabled on noita_dev.exe (find this file on steam Noita folder), it shows more error texts
![here (2)](https://github.com/XM666-Dev/IotaMultiplayer/assets/99076011/392edcc5-0ab0-4ad9-b0c7-6a1e08185b47)
Sorry haven't check github issues

**Comment by XM666-Dev** [comment]
And you should get latest mnee on github
